version: "2"

services:
  mychichair-django:
    restart: always
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    expose:
      - "8000"
    volumes:
      - /usr/src/mychichair
    environment:
      - DJANGO_SETTINGS_MODULE
      - CONTACT_EMAIL
      - CONTACT_EMAIL_PASSWORD
    command: ./docker/django/launch_server.sh

  mychichair-web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - mychichair-django
    links:
      - mychichair-django:web
