FROM python:3.5-alpine
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/mychichair

# Getting node and its dependencies
RUN apk update && apk upgrade
ENV NODE_VERSION=6.9.5-r0
RUN apk add make gcc g++ python libpq python3-dev postgresql-dev libffi-dev libxml2-dev libxslt-dev linux-headers\
    openssl libjpeg-turbo-dev &&\
    apk add nodejs=$NODE_VERSION --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main

# This can be saved on disk to avoid downloading the whole earth everytime we need to install with npm
# Hopefully this will speed up the build
VOLUME /root/.npm
VOLUME /usr/src/mychichair/node_modules

# Enabling local cache for apk
VOLUME /etc/apk/cache

# Python project dependencies and build
VOLUME /root/.cache/pip
RUN mkdir -p /var/python/packages
VOLUME /var/python/packages

# We need these files and node to generate the assets
COPY ./ /usr/src/mychichair/
RUN mkdir -p /usr/src/mychichair/node_modules


CMD npm install ; rm -rf ./static/assets ; mkdir -p ./static/assets && npm run build-assets &&\
    cp -rf ./mychichair/static/assets/* ./static/assets && cp ./webpack-bundle.json ./static
